# Generated by Django 4.1.7 on 2023-03-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_points', models.IntegerField(default=0)),
                ('drive_type', models.CharField(choices=[('Swerve', 'Swerve'), ('West Coast', 'West Coast'), ('Mecanum', 'Mecanum')], max_length=12)),
                ('grid', models.CharField(choices=[('Low Links', 'Low'), ('High Links', 'High'), ('Mid Links', 'Mid'), ('None', 'None')], max_length=11)),
                ('charge_station', models.CharField(choices=[('Untested', 'Untested'), ('Unreliable', 'Unreliable'), ('Reliable', 'Reliable')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('frc_key', models.CharField(max_length=10, unique=True)),
                ('robot_report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='collector.robot', verbose_name='Robot')),
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='frc_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='collector.team', verbose_name='Team'),
        ),
    ]
