# Generated by Django 4.1.7 on 2023-03-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_mobility', models.BooleanField(default=False)),
                ('auto_low', models.IntegerField(default=0)),
                ('auto_mid', models.IntegerField(default=0)),
                ('auto_high', models.IntegerField(default=0)),
                ('auto_attempted', models.IntegerField(default=0)),
                ('auto_scored', models.IntegerField(default=0)),
                ('auto_attempted_cs', models.BooleanField(default=False)),
                ('auto_cs', models.CharField(choices=[('None', 'No Auto'), ('Failed', 'Failed'), ('Docked', 'Docked'), ('Engaged', 'Engaged')], default='None', max_length=13)),
                ('tele_low', models.IntegerField(default=0)),
                ('tele_mid', models.IntegerField(default=0)),
                ('tele_high', models.IntegerField(default=0)),
                ('tele_attempted', models.IntegerField(default=0)),
                ('tele_scored', models.IntegerField(default=0)),
                ('tele_links', models.IntegerField(default=0)),
                ('end_scoring', models.CharField(choices=[('None', 'None'), ('Endgame Failed', 'Failed'), ('Docked', 'Docked'), ('Engaged', 'Engaged'), ('Parked', 'Parked')], default='None', max_length=15)),
                ('driver_rating', models.CharField(choices=[('Really Bad', 'Really Bad'), ('Bad', 'Bad'), ('Moderate', 'Average'), ('Good', 'Good'), ('Really Good', 'Great')], default='Really Bad', max_length=13)),
                ('frc_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='collector.team')),
            ],
        ),
    ]
