# Generated by Django 4.1.7 on 2023-03-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_matchresult_match_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_count', models.PositiveSmallIntegerField(default=0)),
                ('auto_pieces', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('auto_charging', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('auto_mobility', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teleop_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teleop_mid', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teleop_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('engage_attempts', models.IntegerField(default=0)),
                ('endgame_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('driver_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency', to='collector.team')),
            ],
        ),
    ]
