# Generated by Django 4.1.7 on 2023-03-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_remove_matchresult_auto_attempted_cs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_cs',
            new_name='auto_charge_station',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='auto_attempted',
        ),
    ]
