# Generated by Django 4.1.7 on 2023-03-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_rename_auto_cs_matchresult_auto_charge_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_high',
            new_name='auto_cones_high',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_low',
            new_name='auto_cones_low',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_mid',
            new_name='auto_cones_mid',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='tele_high',
            new_name='auto_cubes_high',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='tele_low',
            new_name='auto_cubes_low',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='tele_mid',
            new_name='auto_cubes_mid',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='additional_comments',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='penalties',
            field=models.CharField(choices=[('No penalties', 'No penalties'), ('One or Two penalties', 'One or Two penalties'), ('Multiple Penalties', 'Multiple penalties'), ('A lot of penalties', 'A lot of penalties')], default='No penalties', max_length=20),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='robot_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_cones_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_cones_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_cones_mid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_cubes_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_cubes_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_cubes_mid',
            field=models.IntegerField(default=0),
        ),
    ]
