# Generated by Django 4.1.7 on 2023-03-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_rename_auto_high_matchresult_auto_cones_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='additional_comments',
            new_name='comments',
        ),
    ]
