# Generated by Django 4.1.7 on 2023-03-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_alter_matchresult_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='comments',
            field=models.CharField(blank=True, default=' ', help_text='(optional)', max_length=255),
        ),
    ]
