# Generated by Django 4.1.7 on 2023-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_alter_matchresult_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='grid',
        ),
        migrations.AddField(
            model_name='robot',
            name='game_pieces',
            field=models.CharField(choices=[('Cones', 'Cones'), ('Cubes', 'Cubes'), ('Both', 'Both'), ('None', 'None')], default='None', max_length=5),
        ),
        migrations.AddField(
            model_name='robot',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='robot',
            name='manipulator',
            field=models.CharField(choices=[('Push Bot', 'Push Bot'), ('Claw', 'Claw'), ('Both', 'Both'), ('None', 'Push Bot')], default='None', max_length=8),
        ),
        migrations.AddField(
            model_name='robot',
            name='preffered_grid',
            field=models.CharField(choices=[('Low Links', 'Low'), ('High Links', 'High'), ('Mid Links', 'Mid'), ('None', 'None')], default='None', max_length=11),
        ),
        migrations.AddField(
            model_name='robot',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='robot',
            name='charge_station',
            field=models.CharField(choices=[('Untested', 'Untested'), ('Unreliable', 'Unreliable'), ('Reliable', 'Reliable'), ('None', 'None')], default='None', max_length=13),
        ),
        migrations.AlterField(
            model_name='robot',
            name='drive_type',
            field=models.CharField(choices=[('Swerve', 'Swerve'), ('West Coast', 'West Coast'), ('Mecanum', 'Mecanum')], default='West Coast', max_length=12),
        ),
    ]
