# Generated by Django 4.1.7 on 2023-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_remove_robot_grid_robot_game_pieces_robot_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='manipulator',
            field=models.CharField(choices=[('Push Bot', 'Push Bot'), ('Claw', 'Claw'), ('Both', 'Both')], default='None', max_length=8),
        ),
    ]
