# Generated by Django 4.1.7 on 2023-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_alter_robot_manipulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='game_pieces',
            field=models.CharField(choices=[('Cones', 'Cones'), ('Cubes', 'Cubes'), ('Cones & Cubes', 'Cones & Cubes'), ('None', 'None')], default='None', max_length=13),
        ),
    ]
