# Generated by Django 4.1.7 on 2023-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_alter_robot_game_pieces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_cones_high',
            new_name='auto_high',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_cones_low',
            new_name='auto_low',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='auto_cones_mid',
            new_name='auto_mid',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='auto_cubes_high',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='auto_cubes_low',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='auto_cubes_mid',
        ),
    ]
