# Generated by Django 4.1.7 on 2023-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_teamefficiency_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='driver_rating',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='robot_disabled',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='tele_cones_high',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='tele_cones_low',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='tele_cones_mid',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='tele_cubes_high',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='tele_cubes_low',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='tele_cubes_mid',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='tele_mid',
            field=models.IntegerField(default=0),
        ),
    ]
