# Generated by Django 4.1.7 on 2023-04-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_remove_teamefficiency_driver_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamefficiency',
            name='engage_attempts',
        ),
        migrations.AddField(
            model_name='teamefficiency',
            name='auto_cs_success',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teamefficiency',
            name='teleop_engage_success',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='penalties',
            field=models.CharField(choices=[('None', 'None'), ('One', 'One'), ('Two', 'Two'), ('Three +', 'Three +')], default='None', max_length=20),
        ),
    ]
